fquest/apps/family/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
Description: The URL mapping for the 'family' application.
"""
__author__ = "Ariel Gerardo Rios (ariel.gerardo.rios@gmail.com)"


from django.conf.urls import patterns, url
from django.core.urlresolvers import reverse_lazy
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView
from models import Family, Person
from views import TreeChartView


urlpatterns = patterns('fquest.apps.family',

        # Index

        url(r'^$', TemplateView.as_view(template_name='family_index.html'),
            name='family_index'),

        # Family URL

        url(r'^family/$', ListView.as_view(model=Family), name='family_list'),

        url(r'^family/(?P<pk>\d+)/$', DetailView.as_view(model=Family),
            name='family_detail'),

        url(r'^family/add/$', CreateView.as_view(model=Family,
            template_name='form.html',
            success_url=reverse_lazy('family_list')), name='family_add'),

        url(r'^family/edit/(?P<pk>\d+)/$', UpdateView.as_view(
            model=Family, template_name='form.html',
            success_url=reverse_lazy('family_list')), name='family_edit'),

        # Person URL

        url(r'^person/$', ListView.as_view(model=Person), name='person_list'),

        url(r'^person/(?P<pk>\d+)/$', DetailView.as_view(model=Person),
            name='person_detail'),

        url(r'^person/add/$', CreateView.as_view(model=Person,
            template_name='form.html',
            success_url=reverse_lazy('person_list')), name='person_add'),

        url(r'^person/edit/(?P<pk>\d+)/$', UpdateView.as_view(model=Person,
            template_name='form.html',
            success_url=reverse_lazy('person_list')), name='person_edit'),

        # Tree URL

        # url(r'^tree/(?P<family_id>\d+)/chart/$', tree_chart,
        #     {'restricted': False}, name='tree_chart_complete'),

        url(r'^tree/(?P<family_id>\d+)/chart/$', TreeChartView.as_view(
            restricted=False), name='tree_chart_complete'),

        # url(r'^tree/(?P<family_id>\d+)/chart/restricted/$', tree_chart,
        #     {'restricted': True}, name='tree_chart_restricted'),

        url(r'^tree/(?P<family_id>\d+)/chart/restricted/$',
            TreeChartView.as_view(restricted=True),
            name='tree_chart_restricted'),
)


# vim:ft=python ts=4 tw=80 cc=+1:

fquest/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
Description: Exposes the URI mapping through project applications.
"""
__author__ = "Ariel Gerardo Ríos (ariel.gerardo.rios@gmail.com)"


from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login


admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'fquest.views.home', name='home'),
    url(r'^fquest/family/', include('fquest.apps.family.urls')),
    url(r'^fquest/timeline/', include('fquest.apps.timeline.urls')),

    # Language selection
    url(r'^i18n/', include('django.conf.urls.i18n')),

    # User session
    url(r'^accounts/login/$', login, {'template_name':
        'registration/login.html'}),

    url(r'^accounts/logout/$', logout_then_login),

    # Accout creation
    url(r'^accounts/', include('registration.backends.default.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += patterns('',
            url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
                'document_root': settings.MEDIA_ROOT,
            }),
        )


# vim:ft=python ts=4 tw=80 cc=+1:

fquest/apps/family/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
Description: 'family' application class definitions.
"""
__author__ = "Ariel Gerardo Rios (ariel.gerardo.rios@gmail.com)"


from django.db import models
from django.utils.translation import ugettext as _


NAME_FIELD_MAX_LENGTH = 50

CHOICE_FIELD_MAX_LENGTH = 2


class Family(models.Model):
    """
    Composes the family identification and defines how the leadership is
    composed.
    """

    LEADERSHIP_PATRIARCHAL_CHOICE = u'P'

    LEADERSHIP_MATRIARCHAL_CHOICE = u'M'

    LEADERSHIP_CHOICES = (
            (LEADERSHIP_PATRIARCHAL_CHOICE, _(u'Patriarchal')),
            (LEADERSHIP_MATRIARCHAL_CHOICE, _(u'Matriarchal')),
            )

    sure_name = models.CharField(_(u'Sure Name'),
            max_length=NAME_FIELD_MAX_LENGTH)

    leadership = models.CharField(_(u'Leadership'),
            max_length=CHOICE_FIELD_MAX_LENGTH, choices=LEADERSHIP_CHOICES,
            help_text=_(u"Select how is built the family's leadership; "
                    "patriarchal or matriarchal"))

    class Meta:
        verbose_name_plural = _(u'Families')

    def __unicode__(self):
        return unicode(self.sure_name)

    def roots(self):
        """
        Returns instances of model :model:`family.Person` that represets the
        family roots; the firsts known persons.
        """
        return Person.objects.filter(family__id=self.id, father=None,
                mother=None)


class Person(models.Model):
    """
    Represents the basic information about a person. It defines aspects as
    name, sex, born and decease dates, and family belonging.
    """

    PARENT_HELP_TEXT = _(u'Select the person that will figure as parent, if '
            'it exists in database.')

    SEX_MALE_CHOICE = u'M'

    SEX_FEMALE_CHOICE = u'F'

    SEX_CHOICES = (
            (SEX_MALE_CHOICE, _(u'Male')),
            (SEX_FEMALE_CHOICE, _(u'Female')),
            )

    PICTURE_DEFAULT_height = 44

    PICTURE_DEFAULT_WIDTH = 33

    name = models.CharField(_(u"The person's name"),
            max_length=NAME_FIELD_MAX_LENGTH)

    family = models.ForeignKey(u'Family', related_name=_(u'Family'))

    sex = models.CharField(_(u'Sex'), max_length=CHOICE_FIELD_MAX_LENGTH,
            choices=SEX_CHOICES)

    born_in = models.DateTimeField(_(u'Born date'))

    deceased_in = models.DateTimeField(_(u'Decease date'), blank=True,
            null=True)

    mother = models.ForeignKey('Person', related_name=_(u'Mother'),
            blank=True, null=True, help_text=_(PARENT_HELP_TEXT))

    father = models.ForeignKey('Person', related_name=_(u'Father'),
            blank=True, null=True, help_text=_(PARENT_HELP_TEXT))

    picture = models.ImageField(_(u'Picture'), upload_to='pictures',
            height_field='picture_height', width_field='picture_width',
            blank=True, null=True)

    picture_width = models.PositiveIntegerField(_(u'Width'),
            default=PICTURE_DEFAULT_WIDTH, blank=True, null=True,
            help_text=_(u"The person's picture width, in pixel scale."))

    picture_height = models.PositiveIntegerField(_(u'Height'),
            default=PICTURE_DEFAULT_height, blank=True, null=True,
            help_text=_(u"The person's picture height, in pixel scale."))

    def __unicode__(self):
        return u"%s %s (%s) - %s" % (self.name, self.family.sure_name,
                self.sex, self.born_in)

    def name_complete(self):
        """
        Returns a string with the composition of name and family sure name.
        """
        return '%s %s' % (self.name, self.family.sure_name)

    def family_leader(self):
        """
        Returns the family leader (mother or father), based on the leadership
        definition on class :model:`family.Family`. If it was not defined, then
        return ``None``.
        """
        if self.family.leadership == Family.LEADERSHIP_PATRIARCHAL_CHOICE:
            return self.father
        elif self.family.leadership == Family.LEADERSHIP_MATRIARCHAL_CHOICE:
            return self.mother

        return None

    def parent_by_family(self, family):
        """
        Returns the :model:`family.Person` instance as parent related to the
        current instance by family.
        """
        for p in (self.mother, self.father):
            if p and p.family == family:
                return p

        return None

    def is_alive(self):
        """
        Returns ``True`` if the person is alive, based on the ``deceased_in``
        field value. If ``born_in`` or ``deceased_in`` fields wasn't defined
        then it returns ``None``.
        """
        if not self.born_in and not self.deceased_in:
            return None

        return not self.deceased_in

    def parents(self):
        """
        Retuns a list of :model:`family.Person` related to the current instance
        as progenitors.
        """
        return [self.mother, self.father]

    def brothers(self):
        """
        Retuns a list of :model:`family.Person` related to the current instance
        as brothers/sisters.
        """
        return Person.objects.filter(mother=self.mother,
                father=self.father).exclude(id=self.id).exclude(mother=None,
                        father=None)

    def descendence(self):
        """
        Returns a list of :model:`family.Person` related to the current
        instance as descendence.
        """
        if not self.sex:
            raise ValueError("Cannot determine sex value for current "
                    "instance.")

        return Person.objects.filter(models.Q(mother__id=self.id) if
                self.sex == self.SEX_FEMALE_CHOICE else
                models.Q(father__id=self.id))


# vim:ft=python ts=4 tw=80 cc=+1:

fquest/apps/family/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
Description: View definitions for application 'family'.
"""
__author__ = "Ariel Gerardo Rios (ariel.gerardo.rios@gmail.com)"


# from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.views.generic.base import View
from models import Family, Person


class TreeChartView(View):
    """
    View class implementing how tree charts must fetch required information to
    display in template.
    """

    __TEMPLATE_NAME_FORMAT = 'tree/nodes_%s.html'

    NODE_COMPLETE_TEMPLATE = __TEMPLATE_NAME_FORMAT % 'complete'

    NODE_RESTRICTED_TEMPLATE = __TEMPLATE_NAME_FORMAT % 'restricted'

    TREE_TEMPLATE = 'tree/tree.html'

    restricted = None

    def get(self, request, *args, **kwargs):
        """
        Renders the content for a GET request.
        """
        family_id = kwargs['family_id']

        family = get_object_or_404(Family, id=family_id)

        persons = Person.objects.filter(family__id=family_id) \
                if self.restricted else family.roots()

        node_template = self.NODE_RESTRICTED_TEMPLATE if self.restricted else \
                self.NODE_COMPLETE_TEMPLATE

        return render_to_response(self.TREE_TEMPLATE, {
            'family': family,
            'persons': persons,
            'nodes_template': node_template,
            'restricted': self.restricted
            }, context_instance=RequestContext(request))


# vim:ft=python ts=4 tw=80 cc=+1:

fquest/apps/family/templates/family/family_detail.html
{% extends "base.html" %}

{% load i18n %}

{% block basehead %}
    <title>fquest - {% trans "Family detail" %}</title>
{% endblock %}

{% block basebody %}

  <a href="{% url family_add %}">{% trans "Add other family" %}</a>&nbsp;
  <a href="{% url family_edit object.id %}">
    {% trans "Edit this family" %}
  </a>&nbsp;
  <a href="{% url family_list %}">{% trans "Change family" %}</a>&nbsp;
  <a href="{% url tree_chart_complete object.id %}">
    {% trans "Family tree" %}
  </a>
  <br><br>
  <table border="1">
      <tr>
        <td>{% trans "Sure name" %}</td>
        <td>{{ object.sure_name }}</td>
      </tr>
      <tr>
        <td>{% trans "Leadership" %}</td>
        <td>{{ object.get_leadership_display }}</td>
      </tr>
  </table>
  <p>
    {% trans "Persons in this family" %}:<br>
    <ul>
      {% for p in persons %}
        <li>
          <a href="{% url person_detail p.id %}">{{ p.name_complete }}</a>
        </li>
      {% endfor %}
    </ul>
  </p>
{% endblock %}

fquest/apps/family/templates/family/family_form.html
{% extends "base.html" %}

{% load i18n %}

{% block basehead %}
    <title>fquest - {% trans "Add a Family" %}</title>
{% endblock %}

{% block basebody %}

<form action="" method="post">{% csrf_token %}
  {{ form }}
  <input type="submit" value="create" />
</form>

{% endblock %}

fquest/apps/family/templates/family/family_list.html
{% extends "base.html" %}

{% load i18n %}

{% block basehead %}
    <title>fquest - {% trans "Family list" %}</title>
{% endblock %}

{% block basebody %}

  <a href="{% url family_add %}">{% trans "Add a family" %}</a>

  <table border="1">
    <tr>
      <td>{% trans "Sure name" %}</td>
      <td>{% trans "Leadership" %}</td>
      <td>{% trans "Tree representation" %}</td>
      <td>{% trans "Events representation" %}</td>
    </tr>

    {% for f in object_list %}
      <tr>
        <td><a href="{% url family_detail f.id %}">{{ f.sure_name }}</a></td>
        <td>{{ f.get_leadership_display }}</td>
        <td>
          <a href="{% url tree_chart_complete f.id %}">
            {% url tree_chart_complete f.id %}
          </a>
        </td>
        <td>
          <a href="{% url events_format f.id %}">
            {% url events_format f.id %}
          </a>
        </td>
      </tr>
    {% endfor %}
  </table>
{% endblock %}

fquest/apps/family/templates/family/person_detail.html
{% extends "base.html" %}

{% load i18n %}

{% block basehead %}
    <title>fquest - {% trans "Person detail" %}</title>
{% endblock %}

{% block basebody %}

  <a href="{% url person_add %}">{% trans "Add other person" %}</a>&nbsp;
  <a href="{% url person_edit object.id %}">
    {% trans "Edit this person" %}
  </a>&nbsp;
  <a href="{% url family_detail object.family.id %}">
    {% trans "Go to family detail" %}
  </a>&nbsp;
  <a href="{% url family_list %}">{% trans "Change family" %}</a>
  <br><br>
  <table border="1">
      <tr>
        <td>{% trans "Name" %}</td>
        <td>{{ object.name }}</td>
      </tr>
      <tr>
        <td>{% trans "Sure name" %}</td>
        <td>
          <a href="{% url family_detail object.family.id %}">
            {{ object.family.sure_name }}
          </a>
        </td>
      </tr>
      <tr>
        <td>{% trans "Picture" %}</td>
        <td>
          {% if object.picture %}
            <img src="{{ MEDIA_URL }}{{ object.picture }}">
          {% endif %}
        </td>
      </tr>
      <tr>
        <td>{% trans "Born in" %}</td>
        <td>{{ object.born_in }}</td>
      </tr>
      <tr>
        <td>{% trans "Deceased in" %}</td>
        <td>
          {% if object.deceased_in %}
            {{ object.deceased_in }}
          {% endif %}
        </td>
      </tr>
      <tr>
        <td>{% trans "Mother" %}</td>
        <td>
          {% if object.mother %}
            <a href="{% url person_detail object.mother.id %}">
              {{ object.mother.name_complete }}
            </a>
          {% endif %}
        </td>
      </tr>
      <tr>
        <td>{% trans "Father" %}</td>
        <td>
          {% if object.father %}
            <a href="{% url person_detail object.father.id %}">
              {{ object.father.name_complete }}
            </a>
          {% endif %}
        </td>
      </tr>
      <tr>
        <td>{% trans "Brothers" %}</td>
        <td>
          {% for b in object.brothers %}
            <a href="{% url person_detail b.id %}">{{ b.name_complete }}</a>
          {% endfor %}
        </td>
      </tr>
      <tr>
        <td>{% trans "Descence" %}</td>
        <td>
          {% for d in object.descendence %}
            <a href="{% url person_detail d.id %}">{{ d.name_complete }}</a>
          {% endfor %}
        </td>
      </tr>
  </table>
{% endblock %}